### ISSUE TITLE
document removal of additional props v5

### ISSUE THREAD

**Issue by hartzis** [dogfessional/react-swipeable#154]
- Document removal of additional props being passed down for `<Swipeable />` v5
  - related to possibly bringing this functionality back? #152 

Should we add this functionality back? Does anyone have examples of attributes/props they are specifically relying on?
- `data-test` attributes for testing?
- Are there workarounds?
  - Add an additional `div` with the attributes you need?

**Comment by hartzis** [comment]
PR #155 created

**Comment by beckerei** [comment]
>  Does anyone have examples of attributes/props they are specifically relying on?

We used it to attach `onMouseEnter/MouseLeave` in order to display visual indication for mouse users.
But as discussed in the PR it's easy to work around this by adding an additional `div`.
I can only think of testing with something like `data-testid` where you would not want to add an additional div just for testing purposes.
