### ISSUE TITLE
Handling onClick

### ISSUE THREAD

**Issue by theog** [dogfessional/react-swipeable#38]
Would like to use this component to wrap a toggle button. Having the dual behaviour of swiping and clicking to toggle the buttons on off state.

The issue appears to be when a swipe event occurs, both the onSwipe and the onClick are called, two events  being triggered caused the toggle to update twice.

**Comment by hartzis** [comment]
are you specifically looking for `onClick` from a mouse? Or more like a `tap` from a touch event? If you want the mouse, i'd use `onMouseDown ` instead of `onClick`.

If you want the touch, possibly try [react-touchable](https://github.com/dogfessional/react-touchable) with react-swipeable and working with the `delta` value to not fire swipe events when it is a 'tap'?

**Comment by hartzis** [comment]
We could also contemplate introducing the (react-touchable)[https://github.com/dogfessional/react-touchable] behavior as a prop, `onTap`, into `react-swipeable`. 

This could be a neat option. For example if the 'touches' 'swipe' is less then the `delta` consider it a 'tap' and if the prop `onTap` is present fire it?

**Comment by theog** [comment]
Thank-you for your feedback! Would be great to have one component that handles both! For the meantime, by combining both components together i managed to have both behaviours without either affecting one another. Now tap and swipe appear to work with no side affects.

**Comment by hartzis** [comment]
Glad that solution worked out for you. I created #39 in hopes of adding the `onTap` functionality!

**Comment by jhenriquevissotto** [comment]
I have exactly the same problem. Click and Swipe being executed simultaneously. The library was not programmed correctly to distinguish between the two. How can I get around this?

**Comment by hartzis** [comment]
@jhenriquevissotto been a while since this issue so trying to job my memory.

If you're using the hook, `useSwipeable`, you could possibly put an `onClick` handler on the element you're interested in and call `e.preventDefault()` and/or `e.stopPropagation()` if you want to do something with the click and avoid/skip the swipe functionality.

```
...
const handlers = useSwipeable({ onSwiped: callback });

const onClick = (e) => {
  console.log('clicked');
  e.preventDefault();
  e.stopPropagation();
}

...

return (
  <div {...handlers} >
    <button onClick={onClick} > Click me </button>
  </div>
)
```

Let me know if this helps or not. Still thinking about adding in the `onTap` into v6, #139 .
