### ISSUE TITLE
Y axis and X axis aren't fluid/changing numbers.

### ISSUE THREAD

**Issue by lotusgraham** [dogfessional/react-swipeable#56]
It would be helpful in my case for the x and y property in the state to change as my finger is swiping up the screen. As it is now, it only changes the state to where I touch, as far as I can tell.

here's a gif of what I'm experiencing.. Wondering how I can log a changing state y-axis to swipe for scrolling. In this case I need to add it to transform:translateY

![los2fizpdq](https://cloud.githubusercontent.com/assets/13974084/20284397/eec48a0e-aa8a-11e6-9354-43d8b2438047.gif)

**Comment by hartzis** [comment]
@lotusgraham sweet app! You should be able to get what you are looking for from the args based to your callback in `onSwipingDown` and `onSwipingUp`.

from the readme:
> onSwiping in addition to the swipe delta, `onSwiping` also returns the current absolute X and Y position, as well as the current velocity of the swipe. `this.props.onSwiping(e, deltaX, deltaY, absX, absY, velocity)`

so your prop would probably look like
```
onSwipingDown={(e, deltaX, deltaY, absX, absY, velocity)=>functionThatUsesY(deltaY, absY)}
```

Something like that. Accessing in state via the ref is definitely an anti-pattern and I would suggest trying to avoid it because internal properties and apis could change in the future.

Let me know if this helps.

**Comment by hartzis** [comment]
This is a pretty terrible gif, but in the console you can see the values for the Y changing as I swipe. This is using the example [page](http://dogfessional.github.io/react-swipeable/)

![image](http://g.recordit.co/50rjM1ieX0.gif)
