### ISSUE TITLE
listening touch events on custom component

### ISSUE THREAD

**Issue by dmitrymalakhov** [dogfessional/react-swipeable#89]
Current API only allows you to specify a dom node name. How then I can listening event on my custom components without additional wrapper?

for example:

```
<Swipeable
  component={CarouselSlidesBoxStyled}
  componentProps={{ innerRef: this._saveRefCarouselViewPort }}
  onSwipingLeft={this._handleClickRight}
  onSwipingRight={this._handleClickLeft}
>
  <CarouselSlidesStyled
    innerRef={this._saveRefSlidesContainer}
    offsetSlides={offsetSlides}
  >
    {slides}
  </CarouselSlidesStyled>
</Swipeable>
```

if custom component has innerRef, then Swipeable can use him.

**Comment by hartzis** [comment]
Apologies for the late response.

I think I understand what you're trying to accomplish. I don't know if this is possible since `swipeable` needs to attach it's listeners to a dom element and not a react component internally.

What about having `CarouselSlidesBoxStyled` component use `<Swipeable />` internally and pass either `style` and/or `className` props?

I may not fully understand, but I'm open to an attempt at something. You could create a PR or a [codesandbox](https://codesandbox.io/s/new) with an example and we can discuss?

**Comment by dmitrymalakhov** [comment]
Ok. I'll write an example.

**Comment by hartzis** [comment]
i created a codesandbox, https://codesandbox.io/s/qq7759m3lq. Let me know if this helps with the example.

closing for now, please re-open if needed. cheers 😸
