### ISSUE TITLE
Can't scroll up and down.

### ISSUE THREAD

**Issue by andrisole92** [dogfessional/react-swipeable#94]
Can't scroll up and down on mobile. (Scroll not swipe).

Swiping left and right works, but I would like my page to be also scrollable over Swipeable component.

Can anyone help?

**Comment by hartzis** [comment]
Hey @andrisole92 , curious what version of `react-swipeable` you're using. Since [v4.0.0](https://github.com/dogfessional/react-swipeable/releases/tag/v4.0.0) we default `preventDefaultTouchmoveEvent` to `false` now.

If you're using v4, could you possibly get a https://codesandbox.io/ or some sort of example or code sample i can take a look at?

**Comment by tim-soft** [comment]
Here's an example, I want to _prevent_ react-swipeable events so that I can scroll left<- ->right in this table. 

https://codesandbox.io/s/4j704xjy0

**Comment by hartzis** [comment]
@tim-soft thank you for the codesandbox example. Apologies though because I'm still having a hard time understanding the problem, but I'm glad you found a solution. It seems weird to wrap `<Swipeable>` inside another `<Swipeable>`, but if it works, 🎉  ? lol

What's the `<Swipeable>` tracking when it is wrapped around a table that needs to be scrolled?

There is also a `disabled` prop for `<Swipeable>` that will turn off the component if you know when you want your users to be able to scroll through the table? I also was able to apply an `onScroll` essentially to the table and then set `disabled=true` for `<Swipeable>`, but then how to turn it back on, 🤔 ?

Let me know your thoughts please, i appreciate the feedback and discussion!

**Comment by tim-soft** [comment]
I needed to scroll left/right in the table without triggering my swipe events, since my entire app is wrapped in react-swipeable. Left swipe would trigger a menu to pop out, making scrolling impossible
